// AI-Domain.ai Portfolio – alle Domains
// Nicht zum Verkauf: ki.services, ai-domain.ai, ki-voice.de

const SEDO_PORTFOLIO = "https://sedo.com/search/?showportfolio=af2HkqQtVastoWpIbWUGcOeDllK0YB44axxJ6E0g";

const domains = [

  // ── TIER S – PREMIUM ────────────────────────────────────────────────────
  {
    name: "ai-chatbots.ai",
    price: 28000,
    tier: "S",
    category: "chat",
    badge: "premium",
    desc_de: "Die ultimative KI-Chatbot-Plattform-Domain. Plural + .ai = weltweit einzigartig.",
    desc_en: "The ultimate AI chatbot platform domain. Plural + .ai = globally unique.",
    traffic: null,
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "image-search.ai",
    price: 18000,
    tier: "S",
    category: "core",
    badge: "premium",
    desc_de: "Visual AI / Reverse Image Search – einer der größten AI-Use-Cases 2025.",
    desc_en: "Visual AI / reverse image search – one of the biggest AI use cases of 2025.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "ai-factories.ai",
    price: 18000,
    tier: "S",
    category: "industry",
    badge: "hot",
    desc_de: "DAS Infrastruktur-Buzzword: NVIDIA, Microsoft & Google bauen 'AI Factories' für Milliarden.",
    desc_en: "THE infrastructure buzzword: NVIDIA, Microsoft & Google build 'AI Factories' for billions.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "stock-exchange.ai",
    price: 12000,
    tier: "S",
    category: "finance",
    badge: "premium",
    desc_de: "AI-gestützte Börsenwelt. Für FinTech-Unicorns und Trading-Plattformen der Zukunft.",
    desc_en: "AI-powered stock trading. For FinTech unicorns and next-gen trading platforms.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "agi-agent.ai",
    price: 10000,
    tier: "S",
    category: "agents",
    badge: "hot",
    desc_de: "AGI + Agent + .ai = dreifaches Premium. Das Ziel aller großen AI-Labs in einer Domain.",
    desc_en: "AGI + Agent + .ai = triple premium. The goal of all major AI labs in one domain.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "contentdetection.ai",
    price: 10000,
    tier: "S",
    category: "core",
    badge: "hot",
    desc_de: "Deepfake-Erkennung & AI-Content-Watermarking. EU AI Act macht es zur gesetzlichen Pflicht.",
    desc_en: "Deepfake detection & AI content watermarking. EU AI Act makes it legally mandatory.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "online-doctor.ai",
    price: 10000,
    tier: "S",
    category: "health",
    badge: "premium",
    desc_de: "Telemedizin + AI = Top-VC-Investmentthema. Exact-Match für die digitale Gesundheitsversorgung.",
    desc_en: "Telemedicine + AI = top VC investment theme. Exact match for digital healthcare.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "newtrading.ai",
    price: 9000,
    tier: "S",
    category: "finance",
    badge: "hot",
    desc_de: "Next-Gen AI Trading. Für Handelsplattformen der zweiten Generation.",
    desc_en: "Next-gen AI trading. For second-generation trading platforms.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "ai-invest.ai",
    price: 9000,
    tier: "S",
    category: "finance",
    badge: "premium",
    desc_de: "AI Invest + .ai – perfekt für Robo-Advisor und AI-Investment-Plattformen. Bis 2028 gesichert.",
    desc_en: "AI Invest + .ai – perfect for robo-advisors and AI investment platforms. Secured until 2028.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "ai-portfolio.ai",
    price: 8500,
    tier: "S",
    category: "finance",
    badge: "premium",
    desc_de: "AI Portfolio Management + .ai. Für Vermögensverwalter und FinTech-Startups. Bis 2028.",
    desc_en: "AI portfolio management + .ai. For asset managers and FinTech startups. Until 2028.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "ai-risk.ai",
    price: 8500,
    tier: "S",
    category: "finance",
    badge: "hot",
    desc_de: "EU AI Act = Risk-Management-Pflicht. Für Banken, Versicherungen & Compliance-Startups.",
    desc_en: "EU AI Act = risk management obligation. For banks, insurers & compliance startups.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "aiagent.services",
    price: 8000,
    tier: "S",
    category: "agents",
    badge: "hot",
    desc_de: "Die natürlichste Domain für AI-Agenten-Dienstleister. 354 Agent-Firmen weltweit als Käufer.",
    desc_en: "The most natural domain for AI agent service providers. 354 agent firms worldwide as buyers.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "freesearch.ai",
    price: 8000,
    tier: "S",
    category: "core",
    badge: "premium",
    desc_de: "KI-Suche ohne Bezahlschranke. Für Perplexity-Konkurrenten und Open-Source-Suchprojekte.",
    desc_en: "AI search without paywall. For Perplexity competitors and open-source search projects.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "content-detection.ai",
    price: 7000,
    tier: "S",
    category: "core",
    badge: "hot",
    desc_de: "Mit Bindestrich-Variante für Content Detection. Deepfake & AI-Text-Erkennung.",
    desc_en: "Hyphenated variant for content detection. Deepfake & AI text recognition.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "ai-agents.tools",
    price: 7000,
    tier: "S",
    category: "agents",
    badge: "hot",
    desc_de: ".tools TLD = top für Entwickler-Startups. Agent-Tools-Plattform für den $69-Mrd.-Markt.",
    desc_en: ".tools TLD = top for developer startups. Agent tools platform for the $69B market.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "ethicsagent.ai",
    price: 6500,
    tier: "S",
    category: "agents",
    badge: "hot",
    desc_de: "EU AI Act = AI-Ethics-Compliance Pflicht. Für Governance-Tools und Beratungsunternehmen.",
    desc_en: "EU AI Act = AI ethics compliance mandatory. For governance tools and consulting firms.",
    sedoUrl: SEDO_PORTFOLIO,
  },

  // ── TIER A – HIGH VALUE ──────────────────────────────────────────────────
  {
    name: "airobots.world",
    price: null, // Verhandlungsbasis
    tier: "A",
    category: "core",
    badge: "hot",
    traffic: "280 Uniques/Monat",
    desc_de: "Nachgewiesene Nachfrage: 280 monatliche Besucher. Nur auf Anfrage – Verhandlungsbasis.",
    desc_en: "Proven demand: 280 monthly visitors. On request only – price on application.",
    sedoUrl: SEDO_PORTFOLIO,
    makeOffer: true,
  },
  {
    name: "ai-assistant.world",
    price: 6000,
    tier: "A",
    category: "chat",
    badge: "premium",
    traffic: "261 Uniques/Monat",
    desc_de: "261 monatliche Besucher beweisen: die Nachfrage ist real. Meistgesuchter KI-Begriff + .world.",
    desc_en: "261 monthly visitors prove: demand is real. Most searched AI term + .world.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "ai-dna.world",
    price: 3500,
    tier: "A",
    category: "core",
    badge: "hot",
    traffic: "101 Uniques, 95 Klicks",
    desc_de: "94% Click-Rate – jemand will diese Domain. KI-DNA als Metapher für den Kern jedes AI-Systems.",
    desc_en: "94% click rate – someone wants this domain. AI DNA as metaphor for the core of any AI system.",
    sedoUrl: SEDO_PORTFOLIO,
    makeOffer: true,
  },
  {
    name: "ai-trainer.ai",
    price: 7000,
    tier: "A",
    category: "agents",
    badge: "premium",
    desc_de: "AI Trainer + .ai für Corporate Training, EdTech-Plattformen. Bis 2027 registriert.",
    desc_en: "AI trainer + .ai for corporate training, EdTech platforms. Registered until 2027.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "ai-agents.international",
    price: 5000,
    tier: "A",
    category: "agents",
    badge: null,
    desc_de: "AI Agents + .international – für global operierende KI-Agenturen.",
    desc_en: "AI Agents + .international – for globally operating AI agencies.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "ai-agents.technology",
    price: 4500,
    tier: "A",
    category: "agents",
    badge: null,
    desc_de: "AI Agents + .technology – starkes B2B-Signal für Agent-Hersteller.",
    desc_en: "AI Agents + .technology – strong B2B signal for agent manufacturers.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "agivision.eu",
    price: 4000,
    tier: "A",
    category: "agents",
    badge: "premium",
    desc_de: "AGI Vision für den europäischen Markt. Für EU-AI-Institutionen und Forschungsprojekte.",
    desc_en: "AGI vision for the European market. For EU AI institutions and research projects.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "asi.direct",
    price: 4000,
    tier: "A",
    category: "core",
    badge: "hot",
    desc_de: "ASI (Artificial Super Intelligence) – das Buzzword der nächsten 2 Jahre. Early-Mover-Vorteil.",
    desc_en: "ASI (Artificial Super Intelligence) – the buzzword of the next 2 years. Early mover advantage.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "kindesunterhalt.ai",
    price: 4500,
    tier: "A",
    category: "legal",
    badge: "hot",
    desc_de: "LegalTech DE + .ai. KI-gestütztes Familienrecht – einzigartige Nische für den DACH-Markt.",
    desc_en: "LegalTech DE + .ai. AI-powered family law – unique niche for the DACH market.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "mieterrechte.ai",
    price: 4000,
    tier: "A",
    category: "legal",
    badge: "hot",
    desc_de: "Mieterrecht + AI + .ai. Massive Nachfrage durch Mietpreisdebatte. LegalTech für Deutschland.",
    desc_en: "Tenants' rights + AI + .ai. Massive demand due to rental debate. LegalTech for Germany.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "unterhaltsrechner.ai",
    price: 3500,
    tier: "A",
    category: "legal",
    badge: null,
    desc_de: "AI-Unterhaltsrechner – klarer Use Case für Familienrechts-Portale und LegalTech-Apps.",
    desc_en: "AI maintenance calculator – clear use case for family law portals and LegalTech apps.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "shoppingworld.ai",
    price: 4500,
    tier: "A",
    category: "core",
    badge: null,
    desc_de: "E-Commerce + AI + .ai. Für AI-gestützte Shopping-Plattformen und Retailer-Innovation.",
    desc_en: "E-commerce + AI + .ai. For AI-powered shopping platforms and retail innovation.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "bitcoin-world.ai",
    price: 5500,
    tier: "A",
    category: "finance",
    badge: null,
    desc_de: "Bitcoin + .ai – für die Schnittstelle von Krypto und künstlicher Intelligenz.",
    desc_en: "Bitcoin + .ai – for the intersection of crypto and artificial intelligence.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "bitcoinworld.ai",
    price: 5000,
    tier: "A",
    category: "finance",
    badge: null,
    desc_de: "Bitcoin World + .ai. Crypto-AI-Fusion für Plattformen und Medien.",
    desc_en: "Bitcoin World + .ai. Crypto-AI fusion for platforms and media.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "ai-globalrisk.com",
    price: 3500,
    tier: "A",
    category: "finance",
    badge: null,
    desc_de: ".com + Global Risk AI. Für Unternehmensberatungen und Risikomanagement-Firmen.",
    desc_en: ".com + Global Risk AI. For management consultancies and risk management firms.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "ai-doc.online",
    price: 2500,
    tier: "A",
    category: "health",
    badge: null,
    traffic: "49 Uniques, 46 Klicks",
    desc_de: "94% Click-Rate auch hier. AI-Doktor online – für Telemedizin-Plattformen.",
    desc_en: "94% click rate here too. AI doctor online – for telemedicine platforms.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "ai-health.world",
    price: 3000,
    tier: "A",
    category: "health",
    badge: null,
    desc_de: "AI Health global. Für MedTech-Startups und digitale Gesundheitsplattformen weltweit.",
    desc_en: "AI health global. For MedTech startups and digital health platforms worldwide.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "ki-gesundheit.com",
    price: 2500,
    tier: "A",
    category: "health",
    badge: null,
    desc_de: ".com + KI-Gesundheit auf Deutsch. Premium für den deutschen Gesundheitsmarkt.",
    desc_en: ".com + AI health in German. Premium for the German healthcare market.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "artificialintelligence.technology",
    price: 6000,
    tier: "A",
    category: "core",
    badge: "premium",
    desc_de: "SEO-Exact-Match: 'artificial intelligence' + .technology. Für Content-Plattformen und Agenturen.",
    desc_en: "SEO exact match: 'artificial intelligence' + .technology. For content platforms and agencies.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "ki.services",
    price: null,
    tier: "🔒",
    category: null,
    notForSale: true,
  },
  {
    name: "ai-domain.ai",
    price: null,
    tier: "🔒",
    category: null,
    notForSale: true,
  },
  {
    name: "ki-voice.de",
    price: null,
    tier: "🔒",
    category: null,
    notForSale: true,
  },

  // ── KI DEUTSCH CLUSTER ───────────────────────────────────────────────────
  {
    name: "ki-translator.com",
    price: 3000,
    tier: "A",
    category: "ki-deutsch",
    badge: null,
    desc_de: ".com + KI-Übersetzung auf Deutsch. Für Translation-Startups im DACH-Markt.",
    desc_en: ".com + AI translation in German. For translation startups in the DACH market.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "aichat.jetzt",
    price: 1500,
    tier: "B",
    category: "chat",
    badge: null,
    desc_de: "aichat.jetzt – zeitgemäß und modern. Einzigartiges deutsches .jetzt-TLD.",
    desc_en: "aichat.jetzt – timely and modern. Unique German .jetzt TLD.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "kichat.ai",
    price: 4000,
    tier: "A",
    category: "ki-deutsch",
    badge: "hot",
    desc_de: "Deutsch + .ai = Premium. Für den DACH-Markt mit .ai-Bonus. KI-Chat-Startups.",
    desc_en: "German + .ai = premium. For the DACH market with .ai bonus. AI chat startups.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "kuenstliche-intelligenz.app",
    price: 2500,
    tier: "A",
    category: "ki-deutsch",
    badge: null,
    desc_de: "Deutsches Exact-Match + .app. SEO-Gold für den DACH-Markt.",
    desc_en: "German exact match + .app. SEO gold for the DACH market.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "ki.technology",
    price: 3500,
    tier: "A",
    category: "ki-deutsch",
    badge: null,
    desc_de: "Sehr kurz: ki.technology. Für deutsche Tech-Unternehmen im KI-Bereich.",
    desc_en: "Very short: ki.technology. For German tech companies in the AI sector.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "ki-fabriken.de",
    price: 2000,
    tier: "A",
    category: "ki-deutsch",
    badge: null,
    desc_de: "KI-Fabriken auf Deutsch. Das Pendant zu 'AI Factories' für den deutschen Markt.",
    desc_en: "AI factories in German. The counterpart to 'AI Factories' for the German market.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "aifactories.eu",
    price: 2000,
    tier: "A",
    category: "industry",
    badge: null,
    desc_de: "AI Factories + .eu – Industrie 4.0 für den europäischen Markt.",
    desc_en: "AI Factories + .eu – Industry 4.0 for the European market.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "aiethics.institute",
    price: 3500,
    tier: "A",
    category: "agents",
    badge: "hot",
    desc_de: "AI Ethics Institute – für Forschungsinstitute, Think Tanks. EU AI Act macht es topaktuell.",
    desc_en: "AI ethics institute – for research institutions, think tanks. EU AI Act makes it topical.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "superai.finance",
    price: 3500,
    tier: "A",
    category: "finance",
    badge: null,
    desc_de: "Super AI + .finance = Premium-FinTech. Für AI-Investment-Plattformen.",
    desc_en: "Super AI + .finance = premium FinTech. For AI investment platforms.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "superai.expert",
    price: 3500,
    tier: "A",
    category: "core",
    badge: null,
    desc_de: "Super AI + .expert = Premium-Positionierung für Beratungsunternehmen.",
    desc_en: "Super AI + .expert = premium positioning for consulting firms.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "ai-finance.world",
    price: 1800,
    tier: "A",
    category: "finance",
    badge: null,
    traffic: "40 Uniques/Monat",
    desc_de: "Nachgewiesener Traffic: 40 monatliche Besucher. AI Finance global.",
    desc_en: "Proven traffic: 40 monthly visitors. AI finance global.",
    sedoUrl: SEDO_PORTFOLIO,
  },
  {
    name: "ai-finance.info",
    price: 1500,
    tier: "B",
    category: "finance",
    badge: null,
    traffic: "48 Uniques, 40 Klicks",
    desc_de: "83% Click-Rate! AI Finance Info – nachweislich hohe Kaufbereitschaft.",
    desc_en: "83% click rate! AI finance info – demonstrably high purchase intent.",
    sedoUrl: SEDO_PORTFOLIO,
  },
];

// Nur verkäufliche Domains exportieren
const saleDomains = domains.filter(d => !d.notForSale);

// Kategorien
const categories = {
  all:       { de: "Alle",        en: "All" },
  agents:    { de: "🤖 Agents",   en: "🤖 Agents" },
  finance:   { de: "💰 Finance",  en: "💰 Finance" },
  health:    { de: "🏥 Health",   en: "🏥 Health" },
  chat:      { de: "💬 Chat & AI", en: "💬 Chat & AI" },
  core:      { de: "⚡ AI Core",  en: "⚡ AI Core" },
  industry:  { de: "🏭 Industry", en: "🏭 Industry" },
  "ki-deutsch": { de: "🇩🇪 KI Deutsch", en: "🇩🇪 KI German" },
  legal:     { de: "⚖️ LegalTech", en: "⚖️ LegalTech" },
};
