// Two launch guides (matrix A6). Evidence-led, verified process facts only, no filler.
export interface GuideSection { h: string; p: string[]; list?: string[] }
export interface Guide {
  slug: string;
  title: { en: string; de: string };
  description: { en: string; de: string };
  kicker: { en: string; de: string };
  intro: { en: string; de: string };
  sections: { en: GuideSection[]; de: GuideSection[] };
  updated: string;
}

export const GUIDES: Guide[] = [
  {
    slug: 'how-to-buy-a-premium-domain',
    updated: '2026-09-18',
    title: { en: 'How to buy a premium domain via Sedo', de: 'So kaufen Sie eine Premium-Domain über Sedo' },
    kicker: { en: 'Buyer guide', de: 'Käufer-Guide' },
    description: {
      en: 'A buyer’s walkthrough of a Sedo domain purchase: Buy Now vs. enquiry, Sedo account, payment into Sedo’s neutral account, transfer service, timing and costs.',
      de: 'Der Kaufweg bei Sedo aus Käufersicht: Sofortkauf vs. Anfrage, Sedo-Konto, Zahlung auf Sedos neutrales Konto, Transfer-Service, Registrarwahl, Dauer und Kosten.',
    },
    intro: {
      en: 'Most people buy a domain once. The process at Sedo is well documented on the seller side but rarely explained for buyers. This guide walks through a purchase initiated on AI-DOMAIN.AI step by step, using only what Sedo itself publishes.',
      de: 'Die meisten Menschen kaufen einmal im Leben eine Domain. Der Ablauf bei Sedo ist auf der Verkäuferseite gut dokumentiert, für Käufer aber selten erklärt. Dieser Guide führt Schritt für Schritt durch einen über AI-DOMAIN.AI initiierten Kauf — ausschließlich mit dem, was Sedo selbst veröffentlicht.',
    },
    sections: {
      en: [
        { h: '1. Where the contract is concluded', p: ['AI-DOMAIN.AI is a portfolio site, not a marketplace: it has no checkout and takes no payments. Purchases initiated through AI-DOMAIN.AI are handled securely via Sedo. Sedo, in its own words, "acts neither as a Buyer or Seller, nor as the representative of a Buyer or a Seller, nor as a broker" — the contract is between you and the seller, and Sedo provides the mechanism, the payment handling and the transfer service.', 'For customers residing outside the United States and Canada the contracting party of the Sedo marketplace is Sedo GmbH (Cologne); for customers in the United States and Canada it is Sedo.com, LLC.'] },
        { h: '2. Buy Now or enquiry', p: ['Domains marked "Buy Now at Sedo" carry a binding fixed price set by the seller. Sedo describes it as its fastest purchase method: the seller specifies a binding Buy Now price, the buyer pays the price displayed on the offer page. No negotiation is required — although Sedo notes that buyers may still submit a lower binding offer, which the seller can accept or ignore.', 'Domains marked "enquiry" on AI-DOMAIN.AI are not yet listed for Buy Now. Send a message with the domain name; the sale is then arranged and handled via Sedo as well. Offers made on Sedo are binding.'] },
        { h: '3. The Sedo account', p: ['A free Sedo account is required to buy. Create it before you start so that the purchase is not interrupted by registration.'] },
        { h: '4. Payment', p: ['After the purchase, Sedo sends a payment request. You pay into a neutral account provided by Sedo — Sedo releases the payment to the seller only after the domain has been transferred to you. If the transfer does not go through, Sedo refunds the payment.', 'Sedo may charge a fee for certain payment methods; according to Sedo’s price list, payment by bank transfer carries no buyer fee, while expedited methods can carry a surcharge. Check the current Sedo price list before choosing.'] },
        { h: '5. The transfer', p: ['Sedo’s transfer service is included free of charge for purchases made on the Sedo marketplace. Its transfer specialists work with both parties and their registrars. Once you are registered as the new owner and have full access to the domain, Sedo pays the seller.', 'You can receive the domain at a compatible registrar of your choice — all you need is an account there. For common extensions Sedo states an average of one to ten business days between contract and payout, depending on the cooperation of both sides and the registrars involved; less common extensions can take longer.'] },
        { h: '6. What you acquire — and what you do not', p: ['You acquire the domain itself: the right to use the name for the duration of its registration. A website, logo, content or software is not included. After the transfer you are free to use, resell or redirect the domain.', 'Running costs after the purchase are the annual renewal fees at your own registrar. They depend on the extension and the registrar, and your registrar shows the applicable fee before renewal.'] },
        { h: '7. Prices on AI-DOMAIN.AI', p: ['Prices are shown in EUR and correspond to the Buy Now prices listed at Sedo. Under Sedo’s marketplace terms, the Buy Now price is the end price for the buyer, including any applicable taxes; the amount is confirmed in the Sedo purchase process before you buy. USD figures on this site are approximate conversions for orientation only.'] },
      ],
      de: [
        { h: '1. Wo der Vertrag zustande kommt', p: ['AI-DOMAIN.AI ist eine Portfolio-Website, kein Marktplatz: Sie hat keinen Checkout und nimmt keine Zahlungen entgegen. Käufe, die über AI-DOMAIN.AI initiiert werden, werden sicher über Sedo abgewickelt. Sedo tritt nach eigenen Worten „weder als Käufer oder Verkäufer noch als Vertreter eines Käufers oder Verkäufers noch als Broker“ auf — der Vertrag besteht zwischen Ihnen und der Verkäuferin; Sedo stellt den Mechanismus, die Zahlungsabwicklung und den Transfer-Service.', 'Für Kunden mit Wohnsitz außerhalb der USA und Kanada ist Vertragspartner des Sedo-Marktplatzes die Sedo GmbH (Köln); für Kunden in den USA und Kanada die Sedo.com, LLC.'] },
        { h: '2. Sofortkauf oder Anfrage', p: ['Domains mit „Sofortkauf bei Sedo“ tragen einen verbindlichen Festpreis der Verkäuferin. Sedo beschreibt den Sofortkauf als schnellste Kaufmethode: Die Verkäuferin legt einen verbindlichen Sofortkaufpreis fest, der Käufer zahlt den auf der Angebotsseite angezeigten Preis. Eine Verhandlung ist nicht nötig — Sedo weist allerdings darauf hin, dass Käufer trotzdem ein niedrigeres verbindliches Angebot abgeben können, das die Verkäuferin annehmen oder ignorieren kann.', 'Domains „auf Anfrage“ auf AI-DOMAIN.AI sind noch nicht für den Sofortkauf gelistet. Senden Sie eine Nachricht mit dem Domainnamen; der Verkauf wird dann vereinbart und ebenfalls über Sedo abgewickelt. Angebote bei Sedo sind verbindlich.'] },
        { h: '3. Das Sedo-Konto', p: ['Zum Kauf ist ein kostenloses Sedo-Konto erforderlich. Legen Sie es vor dem Kauf an, damit der Ablauf nicht durch die Registrierung unterbrochen wird.'] },
        { h: '4. Zahlung', p: ['Nach dem Kauf sendet Sedo eine Zahlungsaufforderung. Sie zahlen auf ein von Sedo bereitgestelltes, neutrales Konto — Sedo zahlt den Kaufpreis erst an die Verkäuferin aus, wenn die Domain auf Sie übertragen ist. Kommt die Übertragung nicht zustande, wird der Betrag laut Sedo zurückerstattet.', 'Für bestimmte Zahlungsarten kann Sedo eine Gebühr erheben; laut Sedos Preisliste ist die Zahlung per Überweisung für Käufer gebührenfrei, beschleunigte Zahlungsarten können einen Aufschlag tragen. Prüfen Sie die aktuelle Sedo-Preisliste, bevor Sie wählen.'] },
        { h: '5. Die Übertragung', p: ['Sedos Transfer-Service ist für Käufe auf dem Sedo-Marktplatz kostenlos enthalten. Die Transfer-Spezialisten arbeiten mit beiden Seiten und deren Registraren zusammen. Sobald Sie als neuer Inhaber eingetragen sind und vollen Zugriff auf die Domain haben, zahlt Sedo an die Verkäuferin aus.', 'Sie können die Domain bei einem kompatiblen Registrar Ihrer Wahl entgegennehmen — Sie brauchen dort lediglich ein Konto. Für gängige Endungen nennt Sedo durchschnittlich ein bis zehn Werktage zwischen Vertragsschluss und Auszahlung, abhängig von der Mitwirkung beider Seiten und den beteiligten Registraren; weniger übliche Endungen können länger dauern.'] },
        { h: '6. Was Sie erwerben — und was nicht', p: ['Sie erwerben die Domain selbst: das Nutzungsrecht am Namen für die Dauer der Registrierung. Website, Logo, Inhalte oder Software gehören nicht dazu. Nach der Übertragung können Sie die Domain frei verwenden, weiterverkaufen oder auf ein bestehendes Projekt leiten.', 'Laufende Kosten nach dem Kauf sind die jährlichen Verlängerungsgebühren bei Ihrem eigenen Registrar. Sie hängen von Endung und Registrar ab; Ihr Registrar zeigt die geltende Gebühr vor der Verlängerung an.'] },
        { h: '7. Preise auf AI-DOMAIN.AI', p: ['Preise in EUR entsprechen den bei Sedo gelisteten Sofortkaufpreisen. Nach den Marktplatzbedingungen von Sedo ist der Sofortkaufpreis der Endpreis für den Käufer einschließlich etwaiger anfallender Steuern; der Betrag wird im Sedo-Kaufprozess vor dem Kauf bestätigt. USD-Angaben auf dieser Website sind ungefähre Umrechnungen zur Orientierung.'] },
      ],
    },
  },
  {
    slug: 'ai-domain-valuation',
    updated: '2026-09-18',
    title: { en: 'How AI domains are priced — and how to read a market comparison', de: 'Wie KI-Domains bepreist werden — und wie man einen Marktvergleich liest' },
    kicker: { en: 'Valuation guide', de: 'Bewertungs-Guide' },
    description: {
      en: 'What determines the asking price of a premium AI domain: category term, length, extension, comparable sales — and why single sales and averages must not be confused.',
      de: 'Was den Angebotspreis einer Premium-KI-Domain bestimmt: Kategoriebegriff, Länge, Endung, vergleichbare Verkäufe — und warum Einzelverkäufe und Durchschnitte nicht dasselbe sind.',
    },
    intro: {
      en: 'There is no official price for a domain. What exists is a public record of what buyers have paid for comparable names, and a set of criteria that sellers and buyers both use. This guide explains the criteria behind the prices on AI-DOMAIN.AI and how to read market data without being misled by it.',
      de: 'Es gibt keinen amtlichen Preis für eine Domain. Was es gibt, ist ein öffentlicher Nachweis darüber, was Käufer für vergleichbare Namen gezahlt haben — und Kriterien, die Verkäufer wie Käufer verwenden. Dieser Guide erklärt die Kriterien hinter den Preisen auf AI-DOMAIN.AI und wie man Marktdaten liest, ohne sich von ihnen täuschen zu lassen.',
    },
    sections: {
      en: [
        { h: '1. Asking price, sale price, average — three different things', p: ['An asking price is what the owner asks; a sale price is what one buyer paid for one name on one day; an average is a statistic over many sales, dominated by the many small ones. Mixing them up is the most common mistake in domain "valuations". Every price on AI-DOMAIN.AI is an asking price — it is neither a valuation nor a forecast.'] },
        { h: '2. What the public record shows', p: ['Publicly reported .ai sales in 2025 ranged from five figures to $750,000 (Wisdom.ai, October 2025, via Grit Brokerage) and $600,000 (Cloud.ai, July 2025), with law.ai at $350,000 the largest .ai sale on Sedo that year and Mini.ai at $117,000, also on Sedo. In 2023, agents.ai sold for $125,000 — at the time the largest publicly reported .ai sale. Sources: DNJournal sales charts and, for the Sedo scope, the Sedo/InterNetX Global Domain Report 2026 as reported by SIDN.', 'The Sedo/InterNetX Global Domain Report 2025 lists the ten highest public .ai sales of 2024, led by twin.ai ($95,000), advice.ai ($80,000) and mba.ai ($50,000), and puts the average .ai sale price on Sedo in 2024 at $6,525 (2023: $9,681). That average is a different animal from the headline sales: it is pulled down by hundreds of small transactions.'] },
        { h: '3. The criteria behind an asking price', p: ['The prices in this portfolio were set with a tiered logic. The strongest tier holds category-defining names: .ai domains without a hyphen, three-character labels and double keywords that describe a whole product class. The middle tier holds strong hyphenated .ai names and exact-match terms under geographic or language extensions (for example .de, .ch, .bayern with a German keyword). The third tier holds descriptive names under usable extensions, and the remaining names carry only a modest premium where the extension itself is the limiting factor (.world, .international, .info, .live).'], list: ['Category term: does the name describe a product class (agents, chatbots, health assistant) rather than a brand nobody knows?', 'Length and readability: shorter names and names that spell one term without a hyphen rank higher; hyphens are acceptable where German compound conventions expect them.', 'Extension: .ai for AI companies; country and regional extensions for localised businesses; generic new extensions only with a strong keyword.', 'Comparables: publicly reported sales of similar names, read with their scope and date.', 'Family value: adjacent spellings and extensions that can be bundled protect a brand.'] },
        { h: '4. Registrations are not prices', p: ['The .ai zone grew from 598,007 registered domains (31 January 2025, registry data via the Global Domain Report 2025) to more than one million in January 2026 (Government of Anguilla) — roughly 67 percent in twelve months. That tells you how many organisations use the extension. It says nothing about the price of a single name, and it is not a forecast.'] },
        { h: '5. What a price on this site is not', p: ['It is not a valuation, not an appraisal and not an estimate of a future resale value. It is the owner’s asking price, derived from the criteria above and checked against comparables. If you disagree with it, an enquiry with the domain name is the right next step.'] },
      ],
      de: [
        { h: '1. Angebotspreis, Verkaufspreis, Durchschnitt — drei verschiedene Dinge', p: ['Ein Angebotspreis ist, was die Inhaberin verlangt; ein Verkaufspreis ist, was ein Käufer für einen Namen an einem Tag gezahlt hat; ein Durchschnitt ist eine Statistik über viele Verkäufe, geprägt von den vielen kleinen. Sie zu verwechseln ist der häufigste Fehler bei Domain-„Bewertungen“. Jeder Preis auf AI-DOMAIN.AI ist ein Angebotspreis — weder Bewertung noch Prognose.'] },
        { h: '2. Was der öffentliche Nachweis zeigt', p: ['Öffentlich gemeldete .ai-Verkäufe reichten 2025 von fünfstelligen Beträgen bis 750.000 US-Dollar (Wisdom.ai, Oktober 2025, über Grit Brokerage) und 600.000 US-Dollar (Cloud.ai, Juli 2025); law.ai war mit 350.000 US-Dollar der größte .ai-Verkauf bei Sedo in diesem Jahr, Mini.ai erzielte 117.000 US-Dollar, ebenfalls bei Sedo. 2023 wechselte agents.ai für 125.000 US-Dollar den Besitzer — damals der größte öffentlich gemeldete .ai-Verkauf. Quellen: DNJournal-Verkaufscharts und, für den Sedo-Rahmen, der Sedo/InterNetX Global Domain Report 2026, berichtet von SIDN.', 'Der Sedo/InterNetX Global Domain Report 2025 nennt die zehn höchsten öffentlichen .ai-Verkäufe 2024, angeführt von twin.ai (95.000 $), advice.ai (80.000 $) und mba.ai (50.000 $), und beziffert den durchschnittlichen .ai-Verkaufspreis bei Sedo 2024 mit 6.525 US-Dollar (2023: 9.681 US-Dollar). Dieser Durchschnitt ist etwas anderes als die Schlagzeilen-Verkäufe: Er wird von Hunderten kleiner Transaktionen nach unten gezogen.'] },
        { h: '3. Die Kriterien hinter einem Angebotspreis', p: ['Die Preise dieses Portfolios wurden mit einer gestuften Logik festgelegt. Die stärkste Stufe enthält kategoriebestimmende Namen: .ai-Domains ohne Bindestrich, Drei-Zeichen-Labels und Doppel-Keywords, die eine ganze Produktklasse beschreiben. Die mittlere Stufe enthält starke .ai-Namen mit Bindestrich und Exact-Match-Begriffe unter Geo- und Sprachendungen (etwa .de, .ch, .bayern mit deutschem Keyword). Die dritte Stufe enthält beschreibende Namen unter brauchbaren Endungen; die übrigen Namen tragen nur einen moderaten Aufschlag, weil dort die Endung selbst der begrenzende Faktor ist (.world, .international, .info, .live).'], list: ['Kategoriebegriff: Beschreibt der Name eine Produktklasse (Agents, Chatbots, Health Assistant) statt einer Marke, die niemand kennt?', 'Länge und Lesbarkeit: Kürzere Namen und Namen, die einen Begriff ohne Bindestrich schreiben, stehen höher; Bindestriche sind dort in Ordnung, wo deutsche Kompositum-Konventionen sie erwarten.', 'Endung: .ai für KI-Unternehmen; Länder- und Regionalendungen für lokalisierte Geschäfte; generische neue Endungen nur mit starkem Keyword.', 'Vergleichswerte: öffentlich gemeldete Verkäufe ähnlicher Namen, gelesen mit ihrem Rahmen und Datum.', 'Familienwert: benachbarte Schreibweisen und Endungen, die sich paketieren lassen, schützen eine Marke.'] },
        { h: '4. Registrierungen sind keine Preise', p: ['Die .ai-Zone wuchs von 598.007 registrierten Domains (31. Januar 2025, Registry-Daten laut Global Domain Report 2025) auf über eine Million im Januar 2026 (Regierung von Anguilla) — rund 67 Prozent in zwölf Monaten. Das sagt, wie viele Organisationen die Endung nutzen. Über den Preis eines einzelnen Namens sagt es nichts, und es ist keine Prognose.'] },
        { h: '5. Was ein Preis auf dieser Website nicht ist', p: ['Er ist keine Bewertung, kein Gutachten und keine Schätzung eines künftigen Wiederverkaufswerts. Er ist der Angebotspreis der Inhaberin, abgeleitet aus den obigen Kriterien und gegen Vergleichswerte geprüft. Wenn Sie ihn anders einschätzen, ist eine Anfrage mit dem Domainnamen der richtige nächste Schritt.'] },
      ],
    },
  },
];

export const guideBySlug = (slug: string) => GUIDES.find((g) => g.slug === slug);
